# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 533)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.but_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Footlight MT Light")
        font.setPointSize(9)
        font.setItalic(True)
        self.but_1.setFont(font)
        self.but_1.setObjectName("but_1")
        self.verticalLayout.addWidget(self.but_1)
        self.img1 = ImageView(self.centralwidget)
        self.img1.setObjectName("img1")
        self.verticalLayout.addWidget(self.img1)
        self.but_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Footlight MT Light")
        font.setPointSize(9)
        font.setItalic(True)
        self.but_2.setFont(font)
        self.but_2.setObjectName("but_2")
        self.verticalLayout.addWidget(self.but_2)
        self.img2 = ImageView(self.centralwidget)
        self.img2.setObjectName("img2")
        self.verticalLayout.addWidget(self.img2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comb_img1 = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Footlight MT Light")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.comb_img1.setFont(font)
        self.comb_img1.setObjectName("comb_img1")
        self.verticalLayout_2.addWidget(self.comb_img1)
        self.plt_img1 = ImageView(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setKerning(False)
        self.plt_img1.setFont(font)
        self.plt_img1.setObjectName("plt_img1")
        self.verticalLayout_2.addWidget(self.plt_img1)
        self.comb_img2 = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Footlight MT Light")
        font.setItalic(True)
        font.setKerning(False)
        self.comb_img2.setFont(font)
        self.comb_img2.setObjectName("comb_img2")
        self.verticalLayout_2.addWidget(self.comb_img2)
        self.plt_img2 = ImageView(self.centralwidget)
        font = QtGui.QFont()
        font.setKerning(False)
        self.plt_img2.setFont(font)
        self.plt_img2.setObjectName("plt_img2")
        self.verticalLayout_2.addWidget(self.plt_img2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.clearb = QtWidgets.QPushButton(self.centralwidget)
        self.clearb.setObjectName("clearb")
        self.verticalLayout_3.addWidget(self.clearb)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.splitter_7 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_6)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(26)
        font.setItalic(False)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comb_out = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comb_out.setFont(font)
        self.comb_out.setObjectName("comb_out")
        self.comb_out.addItem("")
        self.comb_out.addItem("")
        self.horizontalLayout_2.addWidget(self.comb_out)
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_5)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.component1 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.component1.setFont(font)
        self.component1.setObjectName("component1")
        self.verticalLayout_4.addWidget(self.component1)
        self.comb_out1 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comb_out1.setObjectName("comb_out1")
        self.comb_out1.addItem("")
        self.comb_out1.addItem("")
        self.verticalLayout_4.addWidget(self.comb_out1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comb_options1 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comb_options1.setObjectName("comb_options1")
        self.verticalLayout_5.addWidget(self.comb_options1)
        self.slider1 = QtWidgets.QSlider(self.layoutWidget1)
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setObjectName("slider1")
        self.verticalLayout_5.addWidget(self.slider1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.component2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.component2.setFont(font)
        self.component2.setObjectName("component2")
        self.verticalLayout_6.addWidget(self.component2)
        self.comb_out2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comb_out2.setObjectName("comb_out2")
        self.comb_out2.addItem("")
        self.comb_out2.addItem("")
        self.verticalLayout_6.addWidget(self.comb_out2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.comb_options2 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comb_options2.setObjectName("comb_options2")
        self.verticalLayout_7.addWidget(self.comb_options2)
        self.slider2 = QtWidgets.QSlider(self.layoutWidget1)
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setObjectName("slider2")
        self.verticalLayout_7.addWidget(self.slider2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label_1 = QtWidgets.QLabel(self.splitter_4)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.splitter_4)
        self.label_2.setObjectName("label_2")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_4 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.out_img1 = ImageView(self.splitter)
        self.out_img1.setObjectName("out_img1")
        self.out_img2 = ImageView(self.splitter)
        self.out_img2.setObjectName("out_img2")
        self.gridLayout.addWidget(self.splitter_7, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 697, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.but_1.setText(_translate("MainWindow", "image 1"))
        self.but_2.setText(_translate("MainWindow", "image 2"))
        self.clearb.setText(_translate("MainWindow", "clear"))
        self.label.setText(_translate("MainWindow", "mixer output to:"))
        self.comb_out.setItemText(0, _translate("MainWindow", "output 1"))
        self.comb_out.setItemText(1, _translate("MainWindow", "output 2"))
        self.component1.setText(_translate("MainWindow", "component 1:"))
        self.comb_out1.setItemText(0, _translate("MainWindow", "image1"))
        self.comb_out1.setItemText(1, _translate("MainWindow", "image2"))
        self.component2.setText(_translate("MainWindow", "component 2:"))
        self.comb_out2.setItemText(0, _translate("MainWindow", "image 1"))
        self.comb_out2.setItemText(1, _translate("MainWindow", "image 2"))
        self.label_1.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "output 1"))
        self.label_5.setText(_translate("MainWindow", "output 2"))
from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
