# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 559)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.label = QtWidgets.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn1.setText("")
        self.btn1.setObjectName("btn1")
        self.verticalLayout.addWidget(self.btn1)
        self.btn2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn2.setText("")
        self.btn2.setObjectName("btn2")
        self.verticalLayout.addWidget(self.btn2)
        self.btn3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn3.setText("")
        self.btn3.setObjectName("btn3")
        self.verticalLayout.addWidget(self.btn3)
        self.btn4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn4.setText("")
        self.btn4.setObjectName("btn4")
        self.verticalLayout.addWidget(self.btn4)
        self.btn5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn5.setText("")
        self.btn5.setObjectName("btn5")
        self.verticalLayout.addWidget(self.btn5)
        self.btn6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn6.setText("")
        self.btn6.setObjectName("btn6")
        self.verticalLayout.addWidget(self.btn6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b1 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b1.setText("")
        self.b1.setObjectName("b1")
        self.horizontalLayout.addWidget(self.b1)
        self.b2 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b2.setText("")
        self.b2.setObjectName("b2")
        self.horizontalLayout.addWidget(self.b2)
        self.b3 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b3.setText("")
        self.b3.setObjectName("b3")
        self.horizontalLayout.addWidget(self.b3)
        self.b4 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b4.setText("")
        self.b4.setObjectName("b4")
        self.horizontalLayout.addWidget(self.b4)
        self.b5 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b5.setText("")
        self.b5.setObjectName("b5")
        self.horizontalLayout.addWidget(self.b5)
        self.b6 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b6.setText("")
        self.b6.setObjectName("b6")
        self.horizontalLayout.addWidget(self.b6)
        self.b7 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b7.setText("")
        self.b7.setObjectName("b7")
        self.horizontalLayout.addWidget(self.b7)
        self.b8 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b8.setText("")
        self.b8.setObjectName("b8")
        self.horizontalLayout.addWidget(self.b8)
        self.b9 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b9.setText("")
        self.b9.setObjectName("b9")
        self.horizontalLayout.addWidget(self.b9)
        self.b10 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b10.setText("")
        self.b10.setObjectName("b10")
        self.horizontalLayout.addWidget(self.b10)
        self.b11 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b11.setText("")
        self.b11.setObjectName("b11")
        self.horizontalLayout.addWidget(self.b11)
        self.b12 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b12.setText("")
        self.b12.setObjectName("b12")
        self.horizontalLayout.addWidget(self.b12)
        self.b13 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.b13.setText("")
        self.b13.setObjectName("b13")
        self.horizontalLayout.addWidget(self.b13)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.label_9 = QtWidgets.QLabel(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(40)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.bt1 = QtWidgets.QPushButton(self.splitter)
        self.bt1.setMinimumSize(QtCore.QSize(0, 200))
        self.bt1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt1.setStyleSheet("background-color:black;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.bt1.setText("")
        self.bt1.setObjectName("bt1")
        self.bt2 = QtWidgets.QPushButton(self.splitter)
        self.bt2.setMinimumSize(QtCore.QSize(0, 200))
        self.bt2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt2.setStyleSheet("background-color:white;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.bt2.setText("")
        self.bt2.setObjectName("bt2")
        self.bt3 = QtWidgets.QPushButton(self.splitter)
        self.bt3.setMinimumSize(QtCore.QSize(0, 200))
        self.bt3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt3.setStyleSheet("background-color:black;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.bt3.setText("")
        self.bt3.setCheckable(False)
        self.bt3.setChecked(False)
        self.bt3.setAutoRepeat(False)
        self.bt3.setAutoExclusive(False)
        self.bt3.setObjectName("bt3")
        self.bt4 = QtWidgets.QPushButton(self.splitter)
        self.bt4.setMinimumSize(QtCore.QSize(0, 200))
        self.bt4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt4.setStyleSheet("background-color:white;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.bt4.setText("")
        self.bt4.setObjectName("bt4")
        self.bt5 = QtWidgets.QPushButton(self.splitter)
        self.bt5.setMinimumSize(QtCore.QSize(0, 200))
        self.bt5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt5.setStyleSheet("background-color:black;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.bt5.setText("")
        self.bt5.setObjectName("bt5")
        self.bt6 = QtWidgets.QPushButton(self.splitter)
        self.bt6.setMinimumSize(QtCore.QSize(0, 200))
        self.bt6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt6.setStyleSheet("background-color:white;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.bt6.setText("")
        self.bt6.setObjectName("bt6")
        self.bt7 = QtWidgets.QPushButton(self.splitter)
        self.bt7.setMinimumSize(QtCore.QSize(0, 200))
        self.bt7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt7.setStyleSheet("background-color:black;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.bt7.setText("")
        self.bt7.setObjectName("bt7")
        self.bt8 = QtWidgets.QPushButton(self.splitter)
        self.bt8.setMinimumSize(QtCore.QSize(0, 200))
        self.bt8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt8.setStyleSheet("background-color:white;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.bt8.setText("")
        self.bt8.setObjectName("bt8")
        self.bt9 = QtWidgets.QPushButton(self.splitter)
        self.bt9.setMinimumSize(QtCore.QSize(0, 200))
        self.bt9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt9.setStyleSheet("background-color:black;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.bt9.setText("")
        self.bt9.setObjectName("bt9")
        self.bt10 = QtWidgets.QPushButton(self.splitter)
        self.bt10.setMinimumSize(QtCore.QSize(0, 200))
        self.bt10.setMaximumSize(QtCore.QSize(50, 16777215))
        self.bt10.setStyleSheet("background-color:white;\n"
"border-style:outset;\n"
"border-width:2px;")
        self.bt10.setText("")
        self.bt10.setObjectName("bt10")
        self.gridLayout.addWidget(self.splitter_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "guitar"))
        self.label_2.setText(_translate("MainWindow", "E"))
        self.label_3.setText(_translate("MainWindow", "B"))
        self.label_4.setText(_translate("MainWindow", "G"))
        self.label_5.setText(_translate("MainWindow", "D"))
        self.label_6.setText(_translate("MainWindow", "A"))
        self.label_7.setText(_translate("MainWindow", "E"))
        self.label_8.setText(_translate("MainWindow", "Fret"))
        self.label_9.setText(_translate("MainWindow", "piano"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
